# Generated by Django 3.2.9 on 2021-11-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='next_of_kin',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_of_kin_tel',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
