# Generated by Django 3.2.9 on 2021-11-26 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_auto_20211124_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 7, 10, 10, 75138, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 7, 10, 10, 75151, tzinfo=utc)),
        ),
    ]
