# Generated by Django 3.2.9 on 2021-11-26 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_auto_20211126_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 7, 18, 31, 933703, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 7, 18, 31, 933717, tzinfo=utc)),
        ),
    ]
