# Generated by Django 3.2.9 on 2021-11-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0010_auto_20211126_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientvitalcard',
            old_name='wieght',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='patientvitalcard',
            name='oxygen_saturation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patientvitalcard',
            name='pulse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientvitalcard',
            name='respiration_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
