# Generated by Django 3.2.9 on 2021-12-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0013_consultation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorreport',
            old_name='notes',
            new_name='Ref',
        ),
        migrations.RenameField(
            model_name='doctorreport',
            old_name='remarks',
            new_name='observations',
        ),
        migrations.RemoveField(
            model_name='doctorreport',
            name='lab_tests',
        ),
    ]
