# Generated by Django 3.2.9 on 2021-12-27 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0016_alter_doctorreport_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='patient',
        ),
        migrations.AddField(
            model_name='labtest',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.consultation'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='tests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
