# Generated by Django 3.2.9 on 2021-12-29 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0025_auto_20211229_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 9, 31, 27, 562511, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
