# Generated by Django 3.2.9 on 2021-12-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0027_auto_20211229_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
