# Generated by Django 3.2.9 on 2022-01-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0029_bill_billbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
