# Generated by Django 3.2.9 on 2022-01-25 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0030_alter_bill_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.billbook'),
        ),
    ]
