# Generated by Django 3.2.9 on 2022-01-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0031_alter_bill_bill_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.CharField(choices=[('CB', 'Consultaiton Bill'), ('RB', 'Registration Bill'), ('PB', 'Pharmacy Bill'), ('LB', 'Laboratory Bill')], max_length=50),
        ),
    ]
