# Generated by Django 3.2.9 on 2022-01-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0032_alter_bill_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
