# Generated by Django 3.2.9 on 2022-01-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0033_remove_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GM', 'General Medicine'), ('OPD', 'Out Patient Department'), ('IP', 'In Patient Service'), ('CD', 'Consultation Department'), ('LB', 'Laboratory'), ('PD', 'Pharmaceutical Department')], max_length=40)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
