# Generated by Django 3.2.9 on 2022-06-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0035_customuser_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialist',
        ),
    ]
